server:
  port: 8081

spring:
  application:
    name: clinicalEngine

  datasource:
    url: jdbc:mysql://localhost:3306/clinical_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis