server:
  port: 8081

spring:
  application:
    name: clinicalEngine
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/clinical_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

wordpress:
  base-url: ${WORDPRESS_URL:http://localhost:8080}
  username: ${WORDPRESS_USER:admin}
  app-password: ${WORDPRESS_APP_PASSWORD:zPyB SYfc qQC6 Twrn PrWk mTOJ}